// FILE: src/core/jobTags/techStackDefinitions.js
// Canonical list of tech-stack tokens to look for in job descriptions.
// Pure data — moved out of techStack.js to keep that file focused on logic.

export const TECH_STACK_DEFINITIONS = [
  // Languages
  { canonical: 'JavaScript', patterns: ['javascript'] },
  { canonical: 'TypeScript', patterns: ['typescript'] },
  { canonical: 'Python', patterns: ['python'] },
  { canonical: 'Java', patterns: ['java'] },
  { canonical: 'Kotlin', patterns: ['kotlin'] },
  { canonical: 'Rust', patterns: ['rust'] },
  { canonical: 'C++', patterns: ['c\\+\\+'] },
  { canonical: 'C#', patterns: ['c#'] },
  { canonical: 'Ruby', patterns: ['ruby'] },
  { canonical: 'PHP', patterns: ['php'] },
  { canonical: 'Swift', patterns: ['swift'] },
  { canonical: 'Scala', patterns: ['scala'] },
  { canonical: 'Dart', patterns: ['dart'] },
  { canonical: 'Elixir', patterns: ['elixir'] },
  { canonical: 'Clojure', patterns: ['clojure'] },
  { canonical: 'Perl', patterns: ['perl'] },
  { canonical: 'Shell', patterns: ['shell'] },
  { canonical: 'Bash', patterns: ['bash'] },
  { canonical: 'SQL', patterns: ['sql'] },
  { canonical: 'HTML', patterns: ['html'] },
  { canonical: 'CSS', patterns: ['css'] },

  // Frontend
  { canonical: 'React', patterns: ['react(?:\\.js)?', 'reactjs'] },
  { canonical: 'Next.js', patterns: ['next\\.js', 'nextjs'] },
  { canonical: 'Vue', patterns: ['vue(?:\\.js)?', 'vuejs'] },
  { canonical: 'Nuxt', patterns: ['nuxt'] },
  { canonical: 'Angular', patterns: ['angular'] },
  { canonical: 'Svelte', patterns: ['svelte'] },
  { canonical: 'Remix', patterns: ['remix'] },
  { canonical: 'Gatsby', patterns: ['gatsby'] },
  { canonical: 'jQuery', patterns: ['jquery'] },
  { canonical: 'Redux', patterns: ['redux'] },
  { canonical: 'Zustand', patterns: ['zustand'] },
  { canonical: 'MobX', patterns: ['mobx'] },
  { canonical: 'Tailwind', patterns: ['tailwind'] },
  { canonical: 'Bootstrap', patterns: ['bootstrap'] },
  { canonical: 'SASS', patterns: ['sass'] },
  { canonical: 'SCSS', patterns: ['scss'] },
  { canonical: 'Webpack', patterns: ['webpack'] },
  { canonical: 'Vite', patterns: ['vite'] },
  { canonical: 'Storybook', patterns: ['storybook'] },

  // Backend
  { canonical: 'Node.js', patterns: ['node(?:\\.js)?', 'nodejs'] },
  { canonical: 'Express', patterns: ['express'] },
  { canonical: 'NestJS', patterns: ['nest\\.?js', 'nestjs'] },
  { canonical: 'Django', patterns: ['django'] },
  { canonical: 'Flask', patterns: ['flask'] },
  { canonical: 'FastAPI', patterns: ['fastapi'] },
  { canonical: 'Spring Boot', patterns: ['spring\\s+boot'] },
  { canonical: 'Spring', patterns: ['spring'] },
  { canonical: 'Rails', patterns: ['ruby\\s+on\\s+rails', 'rails'] },
  { canonical: 'Laravel', patterns: ['laravel'] },
  { canonical: 'ASP.NET', patterns: ['asp\\.?net'] },
  { canonical: 'Gin', patterns: ['gin(?:\\s+framework)?'] },
  { canonical: 'Fiber', patterns: ['fiber'] },
  { canonical: 'Actix', patterns: ['actix'] },
  { canonical: 'Phoenix', patterns: ['phoenix'] },
  { canonical: 'Hono', patterns: ['hono'] },
  { canonical: 'Fastify', patterns: ['fastify'] },
  { canonical: 'GraphQL', patterns: ['graphql'] },
  { canonical: 'REST', patterns: ['rest(?:ful)?'] },
  { canonical: 'gRPC', patterns: ['grpc'] },

  // Databases
  { canonical: 'PostgreSQL', patterns: ['postgresql', 'postgres'] },
  { canonical: 'MySQL', patterns: ['mysql'] },
  { canonical: 'MongoDB', patterns: ['mongodb'] },
  { canonical: 'Redis', patterns: ['redis'] },
  { canonical: 'Elasticsearch', patterns: ['elasticsearch'] },
  { canonical: 'Cassandra', patterns: ['cassandra'] },
  { canonical: 'DynamoDB', patterns: ['dynamodb'] },
  { canonical: 'Firebase', patterns: ['firebase'] },
  { canonical: 'Firestore', patterns: ['firestore'] },
  { canonical: 'Supabase', patterns: ['supabase'] },
  { canonical: 'CockroachDB', patterns: ['cockroachdb'] },
  { canonical: 'SQLite', patterns: ['sqlite'] },
  { canonical: 'MariaDB', patterns: ['mariadb'] },
  { canonical: 'Oracle', patterns: ['oracle'] },
  { canonical: 'SQL Server', patterns: ['sql\\s+server'] },
  { canonical: 'Neo4j', patterns: ['neo4j'] },

  // Cloud + DevOps
  { canonical: 'AWS', patterns: ['aws'] },
  { canonical: 'GCP', patterns: ['gcp', 'google\\s+cloud'] },
  { canonical: 'Azure', patterns: ['azure'] },
  { canonical: 'Docker', patterns: ['docker'] },
  { canonical: 'Kubernetes', patterns: ['kubernetes', 'k8s'] },
  { canonical: 'Terraform', patterns: ['terraform'] },
  { canonical: 'Ansible', patterns: ['ansible'] },
  { canonical: 'Jenkins', patterns: ['jenkins'] },
  { canonical: 'CircleCI', patterns: ['circleci'] },
  { canonical: 'GitHub Actions', patterns: ['github\\s+actions'] },
  { canonical: 'GitLab CI', patterns: ['gitlab\\s+ci'] },
  { canonical: 'Vercel', patterns: ['vercel'] },
  { canonical: 'Netlify', patterns: ['netlify'] },
  { canonical: 'Heroku', patterns: ['heroku'] },
  { canonical: 'DigitalOcean', patterns: ['digitalocean'] },
  { canonical: 'Cloudflare', patterns: ['cloudflare'] },
  { canonical: 'Nginx', patterns: ['nginx'] },
  { canonical: 'Apache', patterns: ['apache'] },
  { canonical: 'Linux', patterns: ['linux'] },

  // Data / ML
  { canonical: 'Pandas', patterns: ['pandas'] },
  { canonical: 'NumPy', patterns: ['numpy'] },
  { canonical: 'TensorFlow', patterns: ['tensorflow'] },
  { canonical: 'PyTorch', patterns: ['pytorch'] },
  { canonical: 'Scikit-learn', patterns: ['scikit-learn', 'sklearn'] },
  { canonical: 'Spark', patterns: ['spark'] },
  { canonical: 'Hadoop', patterns: ['hadoop'] },
  { canonical: 'Kafka', patterns: ['kafka'] },
  { canonical: 'Airflow', patterns: ['airflow'] },
  { canonical: 'dbt', patterns: ['dbt'] },
  { canonical: 'Snowflake', patterns: ['snowflake'] },
  { canonical: 'BigQuery', patterns: ['bigquery'] },
  { canonical: 'Redshift', patterns: ['redshift'] },
  { canonical: 'Databricks', patterns: ['databricks'] },
  { canonical: 'Tableau', patterns: ['tableau'] },
  { canonical: 'Power BI', patterns: ['power\\s+bi'] },
  { canonical: 'Looker', patterns: ['looker'] },
  { canonical: 'Jupyter', patterns: ['jupyter'] },
  { canonical: 'MLflow', patterns: ['mlflow'] },
  { canonical: 'Hugging Face', patterns: ['hugging\\s+face'] },
  { canonical: 'LangChain', patterns: ['langchain'] },
  { canonical: 'OpenAI', patterns: ['openai'] },
  { canonical: 'LLM', patterns: ['llm', 'large\\s+language\\s+models?'] },

  // Mobile
  { canonical: 'React Native', patterns: ['react\\s+native'] },
  { canonical: 'Flutter', patterns: ['flutter'] },
  { canonical: 'SwiftUI', patterns: ['swiftui'] },
  { canonical: 'Jetpack Compose', patterns: ['jetpack\\s+compose'] },
  { canonical: 'Expo', patterns: ['expo'] },
  { canonical: 'Ionic', patterns: ['ionic'] },
  { canonical: 'Xamarin', patterns: ['xamarin'] },
  { canonical: 'Android SDK', patterns: ['android\\s+sdk'] },
  { canonical: 'iOS SDK', patterns: ['ios\\s+sdk'] },

  // Tools / misc
  { canonical: 'Git', patterns: ['git'] },
  { canonical: 'GitHub', patterns: ['github'] },
  { canonical: 'GitLab', patterns: ['gitlab'] },
  { canonical: 'Bitbucket', patterns: ['bitbucket'] },
  { canonical: 'Jira', patterns: ['jira'] },
  { canonical: 'Confluence', patterns: ['confluence'] },
  { canonical: 'Figma', patterns: ['figma'] },
  { canonical: 'Sketch', patterns: ['sketch'] },
  { canonical: 'Postman', patterns: ['postman'] },
  { canonical: 'Swagger', patterns: ['swagger'] },
  { canonical: 'Sentry', patterns: ['sentry'] },
  { canonical: 'Datadog', patterns: ['datadog'] },
  { canonical: 'Grafana', patterns: ['grafana'] },
  { canonical: 'Prometheus', patterns: ['prometheus'] },
  { canonical: 'New Relic', patterns: ['new\\s+relic'] },
  { canonical: 'PagerDuty', patterns: ['pagerduty'] },
  { canonical: 'Slack API', patterns: ['slack\\s+api'] },
  { canonical: 'Stripe API', patterns: ['stripe\\s+api'] },
];
